### ISSUE TITLE
address 404

### ISSUE THREAD

**Issue by RedTeamWing** [mantvydasb/RedTeam-Tactics-and-Techniques#1]
I learned a lot from your article, thank you for sharing, but several addresses have failed.

https://github.com/mantvydasb/Offensive-Security-Cheatsheets/blob/master/sid-shell.c
https://github.com/mantvydasb/Offensive-Security-Cheatsheets/blob/master/raptor/raptor.tar
https://github.com/mantvydasb/Offensive-Security-Cheatsheets/blob/master/raptor_udf2.c

**Comment by neargle** [comment]
@mantvydasb I have the same issue.

**Comment by mantvydasb** [comment]
fixed, thanks!
