### ISSUE TITLE
HELP ShadowAttack

### ISSUE THREAD

**Issue by L0N3W01F007** [mantvydasb/RedTeam-Tactics-and-Techniques#13]
sir do you have any material(Script) regarding this. ShadowAttack(AutoShadow)tool.
refer link :- https://people.engr.tamu.edu/guofei/paper/ShadowAttacks_final-onecolumn.pdf
anyhelp is appreciated

**Comment by mantvydasb** [comment]
No, I do not have anything related to ShadowAttack, sorry.
