### ISSUE TITLE
Hash collision in windows-api-hashing-in-malware tutorial

### ISSUE THREAD

**Issue by YoavLevi** [mantvydasb/RedTeam-Tactics-and-Techniques#14]
Hey,
I've just noticed that the hash function provided in the tutorial is not so good - I found at least two hash collision of different api function names. one of them is this:
![image](https://user-images.githubusercontent.com/60928603/107863336-4d6d7e00-6e5c-11eb-8087-b1372c44bc27.png)
![image](https://user-images.githubusercontent.com/60928603/107863339-54948c00-6e5c-11eb-9af6-b172bd14cbc3.png)
I recommend the following one, written in c by me and inpired by this excellent paper: "The Last Stage of Delirium. Win32 Assembly Components"

 DWORD getHashFromString(char* instring)
{
	char* string = instring;
	DWORD hash = 0xab10f29f;
	while (*string) hash = ((hash << 5) | (hash >> 27)) + *string++;
	//printf("%s: 0x%x\n", string, hash);
	return hash;
}

**Comment by mantvydasb** [comment]
Thanks, I've added a note suggesting the hashing function was not tested for collisions and is only meant to show the concept behind and that you found a collision.
