### ISSUE TITLE
Broken sid-shell url

### ISSUE THREAD

**Issue by mbenardis** [mantvydasb/RedTeam-Tactics-and-Techniques#15]
At [Pentesting Cheatsheets](https://www.ired.team/offensive-security-experiments/offensive-security-cheetsheets), the [sid-shell](https://github.com/mantvydasb/Offensive-Security-Cheatsheets/blob/master/sid-shell.c) url at the NFS Exported Shares paragraph is broken (404).

**Comment by mantvydasb** [comment]
Fixed it inline, thanks!
