### ISSUE TITLE
Untracking the .vscode directory

### ISSUE THREAD

**Issue by AlirezaChegini** [mantvydasb/RedTeam-Tactics-and-Techniques#3]
As you probably know,
using [.gitignore](https://help.github.com/en/articles/ignoring-files) file can prevent .vscode directory from being committing
for example:
```
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
```

**Comment by mantvydasb** [comment]
Thanks, noted.
