### ISSUE TITLE
Empire shells with netntlmv2 relaying

### ISSUE THREAD

**Issue by tuv7041** [mantvydasb/RedTeam-Tactics-and-Techniques#6]
Hi, I think there's a typo on this Article. It says:
"Note that the NetNTLMv2 hashes can only be relayed to the same host they are originating from. You can, however, try cracking them offline and use them on the machine they originated from".
But the whole article shows how to relay an NetNTLMv2 hash to different host. I think you meant "NetNTLMv2 hashes cannot be relay to the same host they are originating from". 

This was fixed with MS08-068 (https://byt3bl33d3r.github.io/practical-guide-to-ntlm-relaying-in-2017-aka-getting-a-foothold-in-under-5-minutes.html).

**Comment by mantvydasb** [comment]
Hi and thanks, I've updated the gitbook -  nice spot! Note that the github may not update at this time, but the gitbook is updated https://ired.team/offensive-security/lateral-movement/empire-shells-with-netnltmv2-relaying
