### ISSUE TITLE
Bug in the code for Reflective DLL Injection

### ISSUE THREAD

**Issue by peta909** [mantvydasb/RedTeam-Tactics-and-Techniques#7]
Hi,
there is a bug in the following line of code (arguments for ReadFile()) for Reflective DLL injection.
`
	LPVOID dllBytes = HeapAlloc(GetProcessHeap(), HEAP_ZERO_MEMORY, dllSize);
	ReadFile(dll, dllBytes, dllSize, NULL, NULL);
`
the 3rd argument for ReadFile() cant be NULL if the 4th is already a NULL.

`	LPVOID dllBytes = HeapAlloc(GetProcessHeap(), HEAP_ZERO_MEMORY, dllSize);
	DWORD outsize;
	ReadFile(dll, dllBytes, dllSize, &outsize, NULL);
`

**Comment by mantvydasb** [comment]
thank you, fixed!
