### ISSUE TITLE
Is there a translation program?

### ISSUE THREAD

**Issue by Mofisto** [mantvydasb/RedTeam-Tactics-and-Techniques#8]
Hey there, I'm going to translate this series of notes, I'm a security beginner and I found this notes are great, I'm going to follow this experiment and make the Chinese version of the notes, I've already done part of it!

[This is my blog](https://wuhash.com/2020-07-01.html)
But, technically, he's not a translator, so maybe he counts as my study record? Because I'm not strictly following your notes, or I'm doing a Chinese project on my own, I don't know if that's possible.

**Comment by mantvydasb** [comment]
Reference the original notes at https://www.ired.team as much as possible, thanks.
